name: salon_appointment
description: Salon Appointment is a Flutter app to save, see, add, edit & remove appointments.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-467.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  equatable: ^2.0.5
  google_fonts: ^3.0.1
  table_calendar: ^3.0.8
  intl: ^0.17.0
  http: ^0.13.5
  shared_preferences: ^2.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf

flutter_intl:
  enabled: true

  arb_dir: lib/core/l10n
  output_dir: lib/core/generated
